### ISSUE TITLE
Diagrama CRC <crud>

### ISSUE THREAD

**Issue by joaosr** [tonylampada/ahhmeus20epoucos#1]
No diagrama CRC senti falta de cards para os controllers. Isso ocorre pelo comportamento dessa aplicação, onde os controllers estão relacionados diretamente com as directivas? há alguma referência que trate mais a fundo o assunto?

**Comment by tonylampada** [comment]
Excelente pergunta @joaosr.

> Isso ocorre pelo comportamento dessa aplicação, onde os controllers estão relacionados diretamente com as directivas?

Muito pertinente essa observação, é isso mesmo! Se eu quisesse evidenciar alguma responsabilidade de um desses controllers, eu certamente teria decidido colocar essa responsabilidade diretamente dentro da caixinha vermelha da diretiva correspondente. Ou seja, nesse caso faz sentido olhar pra Diretiva+controller como uma coisa só.
